apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/phsangam/sample-app-config.git
    targetRevision: main
    path: helm/frontend          # watches this folder
  destination:
    server: https://kubernetes.default.svc
    namespace: uat
  syncPolicy:
    automated:
      prune: true      # removes resources deleted from Git
      selfHeal: true   # if someone manually changes k8s, ArgoCD reverts it
    syncOptions:
      - CreateNamespace=true
